# Operational Security Rules
# Defines restrictions and rules for OPSEC compliance

# Restricted domain patterns (wildcards supported)
restricted_domains:
  - "*.gov"           # Government domains
  - "*.mil"           # Military domains
  - "*.gov.uk"        # UK government
  - "*.gov.au"        # Australian government
  - "*.gov.ca"        # Canadian government
  - "*.edu"           # Educational institutions
  - "*.ac.uk"         # UK academic
  - "*.edu.au"        # Australian academic
  - "*.edu.ca"        # Canadian academic

# Restricted IP ranges (CIDR notation)
restricted_ips:
  - "10.0.0.0/8"      # Private Class A
  - "172.16.0.0/12"   # Private Class B
  - "192.168.0.0/16"  # Private Class C
  - "127.0.0.0/8"     # Loopback
  - "169.254.0.0/16"  # Link-local
  - "224.0.0.0/4"     # Multicast
  - "240.0.0.0/4"     # Reserved

# Sensitive keywords that should trigger warnings
sensitive_keywords:
  - "classified"
  - "secret"
  - "topsecret"
  - "confidential"
  - "internal"
  - "restricted"
  - "sensitive"
  - "private"
  - "proprietary"
  - "classified"

# Authorized targets for high sensitivity scanning
# Only these targets are allowed for high sensitivity operations
authorized_high_sensitivity:
  - "example.com"
  - "test.example.com"
  # Add your authorized targets here

# Restricted targets for medium sensitivity scanning
# These targets are not allowed for medium sensitivity operations
restricted_medium_sensitivity:
  - "sensitive.example.com"
  - "internal.example.com"
  # Add restricted targets here

# Additional OPSEC rules
additional_rules:
  # Maximum number of requests per hour
  max_requests_per_hour: 1000
  
  # Maximum number of targets per scan
  max_targets_per_scan: 100
  
  # Require explicit authorization for high sensitivity
  require_authorization_high: true
  
  # Require explicit authorization for medium sensitivity
  require_authorization_medium: false
  
  # Log all validation attempts
  log_all_validations: true
  
  # Alert on OPSEC violations
  alert_on_violations: true
